PUT http://localhost:3000/users/604e72da78c4ad4fd08dece8
Content-Type: application/json
{
  "enabled": true
}

###

POST https://nateg-demo-server.herokuapp.com/auth/register
Content-Type: application/json

{
  "first_name": "Khalil",
  "last_name": "Mejdi",
  "email": "khalil.mejdi97@gmaile.com",
  "password": "123456",
  "phone": "21345678"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "khalil.mejdi97@gmail.com",
  "password": "123456"
}
###

POST http://localhost:4000/auth/google-auth
Content-Type: application/json

{
  "username": "khalil.mejdi97@gmail.com",
  "password": "123456"
}
