GET http://localhost:3000/projects

###

GET http://localhost:3000/projects/1

###

POST http://localhost:3000/projects
Content-Type: application/json

{
  "title": "Demo title",
  "budge": "300",
  "zone": "tunis",
  "type": "social",
  "moe": "",
  "startDate": "13/03/2021",
  "endDate": "23/03/2021"
}

###

PUT http://localhost:3000/projects/604d2201074134432ce2a43e

{
  "title": "Updated title",
  "budge": "350",
  "zone": "benarous",
  "type": "finance",
  "moe": "N/A",
  "startDate": "13/03/2021",
  "endDate": "23/03/2021"
}

###

DELETE http://localhost:3000/projects/604d2202074134432ce2a43c