GET http://localhost:3000/projects
Content-Type: application/json
Authorization: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imhhc3Nlbi5jaHRhcmFAc3VwY29tLnRuIiwiaWF0IjoxNjE1NzU1ODA1LCJleHAiOjE2MTU3NTk0MDV9.GoYHvHYFKTFQp1N4mU5rmBOOSBZ_jWahw6DUGVHlSXM'
###

GET http://localhost:3000/api/projects/1

###

POST http://localhost:3000/api/projects
Content-Type: application/json

{
  "title": "Demo title",
  "budge": "300",
  "zone": "tunis",
  "type": "social",
  "moe": "",
  "startDate": "13/03/2021",
  "endDate": "23/03/2021"
}

###

PUT http://localhost:3000/api/projects/604e5e881a599320f448b301
Content-Type: application/json

{
  "title": "New project",
  "budge": "350",
  "zone": "benarous",
  "type": "finance",
  "moe": "N/A",
  "startDate": "13/03/2021",
  "endDate": "23/03/2021"
}

###

DELETE http://localhost:3000/api/projects/604e5e881a599320f448b301